import {
  IsEnum,
  IsOptional,
  IsString,
  IsNotEmpty,
  IsObject,
  IsDateString,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { ChecklistItemStatus } from '@prisma/client';

export class UpdateChecklistItemDto {
  @IsOptional()
  @IsEnum(ChecklistItemStatus)
  status?: ChecklistItemStatus;

  @IsOptional()
  @IsString()
  evidence?: string;

  @IsOptional()
  @IsObject()
  clientSubmission?: Record<string, unknown>;

  @IsOptional()
  @IsString()
  blockerReason?: string;

  // Added for the Marketing Dashboard's "overdue promises" KPI -- without
  // a settable dueDate, nothing generated by OnboardingService could ever
  // actually be overdue.
  @IsOptional()
  @IsDateString()
  dueDate?: string;
}

export class ActivateOverrideDto {
  @IsString()
  @IsNotEmpty()
  reason: string;
}

export class ActivateClientDto {
  @IsOptional()
  @ValidateNested()
  @Type(() => ActivateOverrideDto)
  override?: ActivateOverrideDto;
}
