import { Injectable } from '@nestjs/common';
import { Resend } from 'resend';
import { Webhook } from 'svix';
import type {
  EmailProvider,
  SecureAttachmentRef,
} from '../interfaces/email-provider.interface';
import type {
  InboundEmailProvider,
  InboundEmailPayload,
} from '../interfaces/inbound-email-provider.interface';
import type {
  DeliveryStatusProvider,
  ProviderName,
} from '../interfaces/delivery-status-provider.interface';
import { DeliveryAttemptOutcome } from '@prisma/client';

const RESEND_EVENT_TO_OUTCOME: Record<string, DeliveryAttemptOutcome> = {
  'email.delivered': DeliveryAttemptOutcome.SUCCEEDED,
  'email.bounced': DeliveryAttemptOutcome.BOUNCED,
  'email.complained': DeliveryAttemptOutcome.COMPLAINED,
  'email.delivery_delayed': DeliveryAttemptOutcome.UNDELIVERED,
};

// Real reply tokens are generated by ConversationService as
// randomBytes(16).toString('hex') (lowercase hex only), but the local-part
// pattern itself isn't required to be hex -- match any alphanumeric token so
// this doesn't silently break if the token format ever changes. (The brief's
// original `[a-f0-9]+` character class is a strict subset of this and would
// have rejected any token containing a non-hex letter, e.g. its own test
// fixture 'abc123token'.)
const REPLY_LOCAL_PART_RE = /^reply\+([a-zA-Z0-9]+)@/i;

export interface ResendAdapterConfig {
  apiKey: string;
  webhookSecret: string;
  inboundDomain: string;
}

@Injectable()
export class ResendAdapter
  implements EmailProvider, InboundEmailProvider, DeliveryStatusProvider
{
  private client: Resend;

  constructor(private config: ResendAdapterConfig) {
    this.client = new Resend(config.apiKey);
  }

  async sendEmail(params: {
    to: string;
    from: string;
    replyTo?: string;
    subject: string;
    html: string;
    attachments?: SecureAttachmentRef[];
  }): Promise<{ providerMessageId: string }> {
    const result = await this.client.emails.send({
      to: params.to,
      from: params.from,
      replyTo: params.replyTo,
      subject: params.subject,
      html: params.html,
      attachments: params.attachments?.map((attachment) => ({
        path: attachment.path,
        filename: attachment.filename,
        contentType: attachment.contentType,
      })),
    });
    if (result.error || !result.data) {
      throw new Error(
        `Resend send failed: ${result.error?.message ?? 'unknown error'}`,
      );
    }
    return { providerMessageId: result.data.id };
  }

  // Both EmailProvider and InboundEmailProvider declare a single
  // `signatureHeader: string` param, but svix verification needs three
  // separate headers (svix-id/svix-timestamp/svix-signature). The webhook
  // controller (Task 15/16) is expected to JSON.stringify those three
  // headers into one string before calling either verify method here.
  verifyOutboundWebhookSignature(
    rawBody: string,
    signatureHeader: string,
  ): boolean {
    try {
      const headers = JSON.parse(signatureHeader) as Record<string, string>;
      const wh = new Webhook(this.config.webhookSecret);
      wh.verify(rawBody, headers);
      return true;
    } catch {
      return false;
    }
  }

  verifyInboundWebhookSignature(
    rawBody: string,
    signatureHeader: string,
  ): boolean {
    return this.verifyOutboundWebhookSignature(rawBody, signatureHeader);
  }

  parseInboundEmail(rawBody: Record<string, unknown>): InboundEmailPayload {
    // Resend's real `email.received` webhook nests the event payload under
    // `data` (`{ type, created_at, data: { email_id, from, to: string[], ... } }`)
    // -- fall back to rawBody itself so a bare `data` object, or a flat
    // fixture shape (as used in this adapter's own tests), is also accepted.
    const data =
      rawBody.data && typeof rawBody.data === 'object'
        ? (rawBody.data as Record<string, unknown>)
        : rawBody;

    // Resend's real payload's `to` is an array of recipient addresses (a
    // single email can be addressed to more than one inbox on the inbound
    // domain); accept a plain string too for robustness/tests.
    const toRaw = data.to;
    const to = Array.isArray(toRaw) ? (toRaw[0] as string) : (toRaw as string);

    const match = to.match(REPLY_LOCAL_PART_RE);
    return {
      // Resend's webhook envelope uses `email_id`; its GET /receiving/{id}
      // response uses `id` -- accept either.
      providerMessageId: (data.email_id as string) ?? (data.id as string),
      from: data.from as string,
      to,
      subject: data.subject as string,
      // Resend's inbound webhooks do not include the email body -- only
      // metadata. html/text will be null unless the caller already fetched
      // the full message (e.g. via the Resend receiving API) and merged it
      // into the payload before calling this method.
      html: (data.html as string) ?? null,
      text: (data.text as string) ?? null,
      replyToken: match ? match[1] : null,
    };
  }

  normalizeStatus(
    providerName: ProviderName,
    rawEvent: Record<string, unknown>,
  ): DeliveryAttemptOutcome {
    if (providerName !== 'RESEND') {
      throw new Error(`ResendAdapter cannot normalize ${providerName} events`);
    }
    const type = rawEvent.type as string;
    return RESEND_EVENT_TO_OUTCOME[type] ?? DeliveryAttemptOutcome.FAILED;
  }
}
